apiVersion: v1
kind: ConfigMap
metadata:
  app: {{ template "demo-01.name" . }}
  name: webui-config
data:
    nginx.conf: |-
      user  nginx; 
      worker_processes  1; 

      error_log  /var/log/nginx/error.log warn; 
      pid        /var/run/nginx.pid; 

      events { 
          worker_connections  1024; 
      } 
        
      http { 
          include       /etc/nginx/mime.types; 
          default_type  application/octet-stream; 
        
          log_format  main  '$remote_addr - $remote_user [$time_local] "$request" ' 
                            '$status $body_bytes_sent "$http_referer" ' 
                            '"$http_user_agent" "$http_x_forwarded_for"'; 
        
          access_log  /var/log/nginx/access.log  main; 
      
          sendfile        on; 
        
          keepalive_timeout  65; 
        
          server {
              listen       80;
              server_name  localhost;

              location / {
                  root   /usr/share/nginx/html;
                  index  index.html index.htm;
                  sub_filter 'data-api-url="http://localhost:5000/"' 'data-api-url="http://$http_host/api/"'; # rewrite the api URL
                  sub_filter_types text/html;
              }

              # redirect server error pages to the static page /50x.html
              #
              error_page   500 502 503 504  /50x.html;
              location = /50x.html {
                  root   /usr/share/nginx/html;
              }

              # proxy to the API on /api/...
              rewrite ^/api$ http://$http_host/api/ redirect;
              location /api/ {
                  proxy_set_header Accept-Encoding "";
                  proxy_pass     http://127.0.0.1:{{ .Values.webApi.port }}/;
                  # proxy_redirect default;

                  sub_filter 'href="/' 'href="/api/'; # rewrite paths to API endpoints in the index page
                  sub_filter_types text/html;
                  sub_filter_once off;

              }

          }

      } 